export const actions = {
    CREATE: "CREATE",
    UPDATE: "UPDATE",
    DELETE: "DELETE",
    FETCH_ALL: "FETCH_ALL",
    FETCH_BY_SEARCH: "FETCH_BY_SEARCH",
    FETCH_POST: "FETCH_POST",
    COMMENT: "COMMENT"
}